### ISSUE TITLE
Support for comment in .txt files

### ISSUE THREAD

**Issue by jpvincent** [alex-dow/icu-converter#22]
Hi
Happy having found this library, it does help !

It looks like the comments don't work.
From the [official documentation](http://userguide.icu-project.org/locale/resources#TOC-Format-of-Resource-Bundles) the comments, starting with `//`, are allowed

Say I try to parse this `.txt` file :

``` ICU
root{
// that translation can be seen when logued in
  name_took_photo { "Le {takenDate, date, short} {name} {numPhotos, plural,
        =0 {n'a pas pris de photo.}
        =1 {a pris une seule photo.}
        other {a pris # photos.}
      }"
  }
}
```

For now, it throws a SyntaxError : 

``` terminal
[22:39] jpv@mac-jpv:www $ node test-translation.js

/Users/jpv/supv/www/node_modules/icu-converter/src/icu-format-parser.js:2795
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
            ^
SyntaxError: Expected "{" or [ \t\n\r] but "n" found.
```

Thanks

**Comment by alex-dow** [comment]
Sorry for the very late response, I have missed this notice.

I will investigate further.

**Comment by alex-dow** [comment]
indeed, there aren't even unit tests for comments :(

I will get to work on it.

**Comment by alex-dow** [comment]
I've committed a fix to the parser as well as unit tests. v0.1.1 is published now so if you're using npm you can easily update. let me know if you have any further issues.

**Comment by jpvincent** [comment]
I updated and it does work !

many thanks, that helps for the readability of the translation files
